[package]
name = "tirra"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gui"
path = "src/bin/gui.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]
# ICED
iced = { version = "0.13.1", features = ["highlighter", "tokio", "debug"] }

# Sqlite Database
rusqlite = { version = "0.32.0", features = ["bundled"] }

# Date and Time
chrono = "0.4.38"

# Encrpyption
chacha20poly1305 = "0.10.1"
sha2 = "0.10.8"
scrypt = { version = "0.11", default-features = false }
base64 = "0.22.1"
hkdf = "0.12.4"
hmac = "0.12.1"

[profile.release]
strip = true    # Automatically strip symbols from the binary.
panic = "abort"
opt-level = "z"
lto = true
